image:
  file: .gitpod.Dockerfile
tasks:
  - name: Starting Project
    init: cp .env.example .env &&
      composer install &&
      php artisan key:generate
    command: mysql -u root -e "create database badaso" &&
      php artisan badaso:setup --force &&
      npm install &&
      php artisan migrate && php artisan db:seed --class="Database\Seeders\Badaso\BadasoSeeder" &&
      php artisan badaso:admin admin@admin.com --name=admin --username=admin --password=admin --confirm_password=admin --create && npm run dev &&
      php artisan serve
ports:
  - port: 8000
    onOpen: open-preview
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - MehediDracula.php-namespace-resolver
    - junstyle.php-cs-fixer
