image:
  file: .gitpod.Dockerfile
tasks:
  - name: Starting Project
    init: cp .env.example .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      composer install &&
      php artisan key:generate &&
      mysql -u root -e "create database badaso"
    command: php artisan storage:link &&
      php artisan migrate &&
      php artisan db:seed --class="Database\Seeders\Badaso\BadasoSeeder" &&
      php artisan badaso:admin admin@admin.com --name=admin --username=admin --password=admin --confirm_password=admin --create &&
      npm install &&
      npm run dev &&
      php artisan serve
ports:
  - port: 8000
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - MehediDracula.php-namespace-resolver
    - junstyle.php-cs-fixer
    - PKief.material-icon-theme
